version: '3.7'

services:
  geth-bootnode:
    hostname: geth-bootnode
    env_file:
      - .env
    image: cr-geth-client
    build:
      context: .
      args:
        - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
    command:
      --nodekeyhex="b0ac22adcad37213c7c565810a50f1772291e7b0ce53fb73e7ec2a3c75bc13b5"
      --nodiscover
      --ipcdisable
      --networkid=${NETWORK_ID}
      --netrestrict="172.16.254.0/28"
    networks:
      priv-eth-net:
    volumes:
      - bootnode:/root/.ethereum

  geth-node:
    hostname: geth-node
    env_file:
      - .env
    image: cr-geth-client
    depends_on:
      - geth-bootnode    
    command:
      --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@geth-bootnode:30303"
      --allow-insecure-unlock
      --http
      --http.addr="0.0.0.0"
      --http.api="eth,web3,net,admin,personal"
      --http.corsdomain="*"
      --http.vhosts="*" 
      --networkid=${NETWORK_ID}
      --ws 
      --ws.origins="*" 
      --ws.addr="0.0.0.0"
    ports:
      - "8545:8545"
      - "8546:8546"
    networks:
      priv-eth-net:
    volumes:
      - readonlynode:/root/.ethereum

  geth-miner1:
    hostname: geth-miner1
    env_file:
      - .env
    image: cr-geth-client
    depends_on:
      - geth-bootnode
    command:
      --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@geth-bootnode:30303"
      --mine
      --miner.threads=1
      --networkid=${NETWORK_ID}
    networks:
      priv-eth-net:
    volumes:
      - miner1:/root/.ethereum
  
  geth-miner2:
    hostname: geth-miner2
    env_file:
      - .env
    image: cr-geth-client
    depends_on:
      - geth-bootnode
    command:
      --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@geth-bootnode:30303"
      --mine
      --miner.threads=1
      --networkid=${NETWORK_ID}
    networks:
      priv-eth-net:
    volumes:
      - miner2:/root/.ethereum

  postgres:
    build:
      context: .
      dockerfile: ./docker/db
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      priv-eth-net:
  
  explorer:
    build:
      context: .
      dockerfile: ./docker/explorer
    restart: "no"
    tty: true
    environment:
      - DATABASE_URL=ecto://postgres:@postgres/explorer?ssl=false
      - ETHEREUM_JSONRPC_HTTP_URL=http://geth-node:8545
      - ETHEREUM_JSONRPC_WS_URL=ws://geth-node:8546 
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - geth-miner1
    networks:
      priv-eth-net:
    volumes:
      - explorer:/opt/app/logs
      - explorer:/var/lib/postgresql/data

volumes:
  bootnode:
  readonlynode:
  miner1:
  miner2:
  postgres-data:
  explorer:

networks:
  priv-eth-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.254.0/28